### ISSUE TITLE
Can't install on Revit 2015 + Dynamo 0.9.0.3067

### ISSUE THREAD

**Issue by truevis** [ksobon/Bumblebee#11]
Keep getting message that Bumblebee is for a newer version of Dynamo unless I go back to Oct 2015 build. Even with that build, still not working.

![image](https://cloud.githubusercontent.com/assets/3574046/13031800/f371d35c-d2a6-11e5-9ee8-96c5fdc974a4.png)

Suggestions welcome.

**Comment by ksobon** [comment]
Latest bumblebee was built on dynamo 0.9.1 release candidate. Install that and it should work well. This message can be disregarded. Just click ok.

**Comment by ksobon** [comment]
were you able to get it installed properly?

**Comment by truevis** [comment]
I haven't used it recently, but last time I tried, I installed newer Dynamo
and it worked.

One thing I'd suggest is to publish working DYN examples (that can be
downloaded) using your nodes.

I'll be using BB again, soon, to write Excel.

**Comment by ksobon** [comment]
Will do that. Thanks!
