### ISSUE TITLE
"Excel Read" from Bumblebee

### ISSUE THREAD

**Issue by JPDOliveira** [ksobon/Bumblebee#12]
Hi!
I’m trying to use the Bumblebee package to read data from excel in a specific range of cells, the problem is that it gives me an error which I have no ideia how to solve it.
So see for yourself:
[Dynamo and Excel files](http://dynamobim.org/forums/topic/excel-read-from-bumblebee/#post-38838)

Best regards

**Comment by JPDOliveira** [comment]
Hi Konrad,

Did you solve this bug?

Regards,
João

**Comment by ksobon** [comment]
Please see my answer in the Dynamo forum thread or here: 

It's the encoding for strings that excel uses that causes the issue. Specifically your file path contains some special characters that excel wasn't able to decode. I fixed it by specifying <code>Unicode()</code> encoding manually for the workbook open functions. 

Thanks for posting! 

```python
if filePath == None:
			# run excel in live mode
			xlApp = LiveStream()
			live = True
		else:
			# run excel from file on disk
			xlApp = SetUp(Excel.ApplicationClass())
			if os.path.isfile(unicode(filePath)):
				xlApp.Workbooks.open(unicode(filePath))
			live = False			
```

**Comment by ksobon** [comment]
please test this solution and report back so i can incorporate that into bumbleee. Cheers!

**Comment by ksobon** [comment]
check latest bumblebee. should be fixed.

**Comment by JPDOliveira** [comment]
Working Perfectly!!
Many thanks Konrad.

Regards
