### ISSUE TITLE
Read Excel does not update

### ISSUE THREAD

**Issue by JPDOliveira** [ksobon/Bumblebee#16]
The read excel from Bumblebee package doesn’t update the data just by modifying the excel file for manual or automatic run.
So, you have to modify something in the dynamo file (e.g. put “Runit” false and then true again) in order to get the data updated again.

[Files/Images](http://dynamobim.org/forums/topic/problem-with-read-excel-bumblebee-package/#post-42940)

Best Regards.

**Comment by ksobon** [comment]
It should support File.FromFilePath() now which allows for watching changes made to the excel files on your drive. It still doesn't support live updates for changes made to excel when in live mode.
