### ISSUE TITLE
Issue with special characters in file names

### ISSUE THREAD

**Issue by andydandy74** [ksobon/Bumblebee#17]
Apparently BB doesn't like those pesky foreign characters in filenames. Using a German Umlaut like "ü" will throw the following exception in the line ```if os.path.isfile(str(filePath)):``` :
```
UnicodeDecodeError: ('unknown', u'\xfc'. 0, 1, '')
```

**Comment by ksobon** [comment]
Do you know which node specifically? I think i cleaned that up with this: https://github.com/ksobon/Bumblebee/issues/14 must be an omission.

**Comment by andydandy74** [comment]
Ah, I must've missed that. We're still on your last 0.9.0 compatible version and can't upgrade. I think I'll try a more recent version and replace the new DLL's with their older 0.9.0 compatible counterparts.
