### ISSUE TITLE
Problem with Read Excel after AZcolumn - Bumblebee Package

### ISSUE THREAD

**Issue by ElisabettaCaterina** [ksobon/Bumblebee#19]
Hi All,
i am trying to read a specific range of data with the Bumblebee node.
Actually i have a problem trying to read ranges over the AZ column.

![excelsheet](https://cloud.githubusercontent.com/assets/20029551/16178641/5e7bd43a-364e-11e6-9ed8-23f5bce2f8ae.PNG)

I notice that, after the AZ the reading process is quite strange. Probably i didn't set the correct INPUT, i don't know.

![excel problem reading range](https://cloud.githubusercontent.com/assets/20029551/16178640/50ca82fa-364e-11e6-9b50-11f28988af3d.png)

Thanks for the attention
Elisabetta

**Comment by ksobon** [comment]
Yes, this was a bug with the <code> ConvertChar()</code> method: 

```Python
def ConvertChar(char):
    num = 0
    for c in char:
        if c in string.ascii_letters:
            num = num * 26 + (ord(c.upper()) - ord('A')) + 1
    return num
```

I was able to fix it and will post an update to Package Manager. It should work just fine now, just re-install latest Bumblebee from PM.
