### ISSUE TITLE
BB nodes will return null if not located in default packages folder 

### ISSUE THREAD

**Issue by mkdrafter** [ksobon/Bumblebee#21]
Im currently experiencing same issue as: https://github.com/ksobon/Bumblebee/issues/15

I am using Dynamo 1.0 and Bumblebee 2016.6.30. I posted screenshots to the Dynamo forum.

https://forum.dynamobim.com/t/bumblebee-null-values-w-custom-installation-location-on-a-network-drive/5400

**Comment by ksobon** [comment]
This should be fixed with the latest implementation that @dimven supplied.
