### ISSUE TITLE
NameError in WriteExcel

### ISSUE THREAD

**Issue by Lexiko** [ksobon/Bumblebee#24]
Hi Konrad, I tried using Bumblebee to export so Revit data but keep getting the following error. I replicated it on your simple Primer example.

![image](https://cloud.githubusercontent.com/assets/18419461/18945916/ed5cc210-866f-11e6-932e-04e167e916f9.png)

On Revit 2016 U6 R2 and Dynamo 1.1.0.2094 with Bumblebee 2017.11.2

**Comment by jdnelsonkc** [comment]
Hi Konrad and Lexiko, 
I am having this issue on Dynamo 1.2 as well. Bumblebee 2017.12.1. We tried adding import os to the beginning of the custom python node, but the result was "null".

We did however find a working solution here and hope this helps you as well:
https://forum.dynamobim.com/t/package-bumblebee-name-os-is-not-defined/5989/16

**Comment by ksobon** [comment]
Fixed: 

![image](https://cloud.githubusercontent.com/assets/529781/25776996/1c710f28-329d-11e7-9836-e32784532ff7.png)

Look for this version: 

![image](https://cloud.githubusercontent.com/assets/529781/25776999/3354dbde-329d-11e7-8fdf-66dd5d07097d.png)
