### ISSUE TITLE
cannot get bumblebee to work

### ISSUE THREAD

**Issue by Risingson** [ksobon/Bumblebee#25]
![image](https://cloud.githubusercontent.com/assets/5108701/19233851/67454a72-8ee8-11e6-9102-2a0e10da8c61.png)

or eg:

![image](https://cloud.githubusercontent.com/assets/5108701/19234120/df2a2174-8ee9-11e6-8ab9-4be078446bed.png)

what could be wrong ?

Bumblebee 2017.11.2 / dynamo 1.1

**Comment by ksobon** [comment]
Input to "Search Value Get Row" node needs to be a list. 

![image](https://cloud.githubusercontent.com/assets/529781/25776985/913482b4-329c-11e7-877c-069d5191ca4f.png)

Please put curly brackets around your input `{"A"}`
