### ISSUE TITLE
Make Bumblebee version-neutral

### ISSUE THREAD

**Issue by andydandy74** [ksobon/Bumblebee#26]
Hey Konrad,
when running Bumblebee in Dynamo 1.3 I get an error that the Protogeometry assembly cannot be added.
The cause for this is that the Dynamo version is hardcoded in bumblebee.py
With the following snippet this should not be a problem anymore:
```
from System.Reflection import Assembly
dynamo = Assembly.Load('DynamoCore')
dynamoversion = str(dynamo.GetName().Version)[:3]

sys.path.append(r"C:\Program Files\Dynamo\Dynamo Core\\"+dynamoversion)
```
(based on: https://forum.dynamobim.com/t/what-current-version-of-dynamo/10934/9)
I would have submitted a PR but there seem to be several versions of bumblebee.py in the repo and I didn't want to break anything... ;-)

**Comment by ksobon** [comment]
This looks like a viable solution. I will try and implement that. Sorry for the inconvenience.

**Comment by ksobon** [comment]
This was addressed here: 

![image](https://cloud.githubusercontent.com/assets/529781/25776971/107278c0-329c-11e7-9d19-75e90f49e4c3.png)

Thanks!
