### ISSUE TITLE
Newer Version Compatibility with Dynamo 2.0.4

### ISSUE THREAD

**Issue by BJozi** [ksobon/Bumblebee#40]
I'm updating packages and currently on an older version (2019.2.1), is the latest version (2021.25.3) compatible with Dynamo V2.0.4 and Revit 2019?

I know from other packages, typically it's ok if there are no API related changes to update/use the most current version.

**Comment by ksobon** [comment]
Again, try it out and report here if you have an actual issue. I don't know if there are any from top of my head. There a dozen different Dynamo versions out there. I can't test against them all.
